fix
slowtec/tokio-modbus pull request #105
Opened 2021-12-04 17:46 UTC by justinyhuang

the byte count value resides in the 7th byte of the adu buf, instead of the 5th. this commit fixes it

2021-12-04 20:38 UTC, flosse commented
@justinyhuang thanks for contributing! Would you mind to adjust the test as well?

2021-12-04 21:32 UTC, uklotzde requested changes
I can confirm that according to the [spec,  pp.29-31](https://www.modbus.org/docs/Modbus_Application_Protocol_V1_1b3.pdf) the byte count for function code 0x0F and 0x10 is in the 7th instead of the 5th byte of the ADU. Obviously, no one ever tried to write multiple registers yet. Maybe we got confused by the literal value `4` of the example ;)

Please fix and (if sensible) extend the tests.

2021-12-04 21:35 UTC, uklotzde commented
Please amend the commit, because only commits that build without CI failures should be merged.

@flosse We should also backport this fix to v0.4.x after merging.

2021-12-05 04:13 UTC, justinyhuang commented
Sure. I will try to update the tests.
Also I tested writing multiple registers with Modbus TCP, which works just fine. So I believe it is just the RTU that is not working correctly.

2021-12-05 05:01 UTC, justinyhuang commented
OK I have run `cargo test --features sync` locally and the tests appear passed. 
as a "first-time contributor" I could not kick off CI tests in this repo, thus could you please help approving running the workflows and see if they pass this time?

2021-12-05 09:34 UTC, uklotzde approved these changes
Thank you! LGTM

I will squash the commits and adjust the commit message.

2021-12-05 09:38 UTC, merged