Fix multiplication overflow for function 1 and 2
slowtec/tokio-modbus pull request #87
Opened 2021-08-12 07:41 UTC by lancechentw

The original code calculated required buffer space for decoded values by
mutiplying `byte_count` by 8. Since `byte_count` was given the type
`u8`, the multiplication result would overflowed if `byte_count` is
greater than 31. In other words, if more than 248 coils/discrete inputs
were requested.

This PR cast `byte_count` to u16 before it is used to calculate the
required buffer space, thus prevents the overflow.

2021-08-12 08:02 UTC, uklotzde requested changes
Thank your for finding and fixing this serious issue!

Would it be possible to detect the overflow with a unit test to prevent regressions?

2021-08-12 08:34 UTC, uklotzde commented
You can ignore the clippy warnings. These will finally be fixed by #88.

2021-08-12 09:07 UTC, lancechentw commented on src/codec/mod.rs
> +                let quantity = byte_count as u16 * 8;
Thanks for the feedback! I will fix this and try to add a test case later today.

2021-08-12 09:29 UTC, uklotzde commented
@flosse Backport this fix and publish v0.4.1?

2021-08-12 15:38 UTC, lancechentw commented on src/codec/mod.rs
> +                let quantity = byte_count as u16 * 8;
This is fixed and test cases are added in the latest commits. Please let me know if the fixes are preferred to be squashed.

2021-08-13 09:23 UTC, uklotzde approved these changes
Thank you for walking the extra mile by adding regression tests!

2021-08-13 09:25 UTC, uklotzde commented
I'll stash the commits and fix the formatting issues while rebasing.

2021-08-13 09:35 UTC, uklotzde commented
Merged.

2021-08-13 09:35 UTC, closed without merging